name: Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code formatting
        run: pnpm format:check

      - name: Check assets formatting
        run: pnpm format:assets:check

      - name: Check ESLint
        run: pnpm lint:check

      - name: Check Stylelint
        run: pnpm stylelint:check

      - name: Check types
        run: pnpm type-check

      - name: Build
        run: pnpm build-only
